### PR TITLE
SunShadesCalculator Example for Hydra

### PR DESCRIPTION
**Pull request by ayezioro**

### CODE REVIEW

**Comment by ayezioro** [comment]
Hi @chriswmackey,
Trying to upload an example for the SunShadesCalculator.
Hopefully it went through smoothly.
-A.

**Comment by chriswmackey** [comment]
@ayezioro ,
This is not the way to add new Hydra examples. You don't need to send a pull request or have anyone check your example. You just fork the master Hydra branch and add your example. See this tutorial video here:

https://youtu.be/bt34UvzLwgY

-Chris

**Comment by ayezioro** [comment]
Sorry @chriswmackey and thankyou.
-A.

**Comment by chriswmackey** [comment]
It's all good.  Let me know when you have the example up and we can include a link to it in the release notes that will be posted either today or tomorrow.

**Comment by ayezioro** [comment]
I see that the example is already there. So no need to upload again. Right?

**Comment by chriswmackey** [comment]
Correct.  I see that you updated it here:
http://hydrashare.github.io/hydra/viewer?owner=ayezioro&fork=hydra&id=SunShadesCalculator
I'll include a link to it in the release notes.

**Pull request closed without merging**
